name: Get Path Test

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get path
        id: get-path
        uses: /sub-apps
      - name: Display result
        run: |
          echo "path -> $DIRPATH"
        env:
          DIRPATH: ${{ steps.get-path.outputs.dir-path }}
